name: V1 Tests

on:
  - pull_request_target

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: log untrusted output
        run: |
          echo "CHROME_PATH=yellow" >> $GITHUB_ENV
      - name: Test
        run: node index.js
      - name: Audit URLs using Lighthouse
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
           https://deploy-preview-$PR_NUMBER--docusaurus-2.netlify.app/
          configPath: ./.github/workflows/v2-lighthousesrc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
        env:
          PR_NUMBER: ${{ github.event.pull_request.number}}
      # Not useful to build v1 site because tests already build v1 (packages/docusaurus-1.x/lib/__tests__/build-files.test.js)
